---
- name: Ensure Java is installed
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes
  become: yes

- name: Ensure Git is installed
  apt:
    name: git
    state: present
    update_cache: yes
  become: yes

- name: Install AWS CLI v2
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp
    remote_src: yes
  become: yes

- name: Install AWS CLI
  command: /tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
  become: yes

- name: Ensure Jenkins repository is added
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.list
    dest: /etc/apt/sources.list.d/jenkins.list
  become: yes

- name: Import Jenkins GPG key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  become: yes
  notify: Start Jenkins

- name: Install Jenkins plugins
  command: >
    java -jar /usr/share/java/jenkins.war --httpPort=8080 --prefix=/ install-plugin {{ item }}
  loop:
    - git
    - aws-credentials
    - kubernetes
  become: yes
  ignore_errors: true

- name: Install kubectl
  get_url:
    url: "https://dl.k8s.io/release/{{ lookup('pipe', 'curl -L -s https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
  become: yes