---
- name: Deploy MCP Server on EKS
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    environment: "{{ env | default('dev') }}"
    task: "{{ task | default('all') }}"
    ecr_registry: "{{ ecr_registry | default(lookup('env', 'ECR_REGISTRY')) }}"
    ecr_repository: "{{ ecr_repository | default(lookup('env', 'ECR_REPOSITORY')) }}"
    git_commit: "{{ git_commit | default(lookup('env', 'GIT_COMMIT')) }}"
    aws_region: "{{ aws_region | default(lookup('env', 'AWS_DEFAULT_REGION')) }}"
    rds_endpoint: "{{ rds_endpoint | default('') }}"
    redis_endpoint: "{{ redis_endpoint | default('') }}"
    project_name: "mcp-server"
    cluster_name: "mcp-server-eks-cluster-{{ environment }}"
    database_secret: "mcp-server-jenkins-ansible-key-{{ environment }}"
    
  tasks:
    - name: Configure Jenkins
      include_role:
        name: jenkins
      when: task == "jenkins_config" or task == "all"
      
    - name: Deploy to EKS
      include_role:
        name: eks
      when: task == "prepare_eks" or task == "all"